{% set name = "urlquote" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b961aced6d749cac738c84748acf5fa236a1311d3805ecce58ef397a040fd96

build:
  number: 0
  skip: True  # [win and py2k]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - rust
  host:
    - python
    - setuptools_scm
    - milksnake
    - pip
  run:
    - python
    - six
    - milksnake

test:
  imports:
    - urlquote
    - urlquote.quoting


about:
  home: https://github.com/blue-yonder/urlquote
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fast percent encoding / decoding for python.'
  description: |
    urlquote is not intended to be a replacement for urllib. urllib is part of the Python standard
    library and should be your go-to choice to quote and unquote URLs. However, should quoting or
    unquoting of URLs be known to be a performance bottleneck and you are fine with the encodings
    provided, then by all means have fun using this library.
  doc_url: https://github.com/blue-yonder/urlquote/blob/v1.1.1/README.md
  dev_url: https://github.com/blue-yonder/urlquote

extra:
  recipe-maintainers:
    - pacman82
    - xhochy
