travis:
  secure:
    BINSTAR_TOKEN: AG2UyaG/clEQH8luz2yNNydNz9oqF3FKqRxcZWMlye7Pr/kM3mcZsK3n9/0Bkm9wVkkm3L3GUOTdhm+BRx8TAfgU/V/JeZXgE6KcDWjgBDVX91Bp4waS1m/pnfyQcXK7aWx4mtRb6HGPcftEubou9AvyBmEB0zLDJk7ujpPWktdM5B3DlBlPCvUU0WUZYqvQAycyCHgsgk2FPow3vosq5iiEAZ5GDkyjSNwDpdno1/HA9sd9jJF4xv74BWruvJWpYZ8GO69gHvZfnyaaL/jMStb9qDssjiMM4Fp1d/RLeHd0akxWSi+9LlE1WJiEL0ZMI1U3cQdG8aGk1ttsNaB2Q2nj6ZW+IuarAejtVQAqRTE47emCtS8Tg2cVBQJNqPpbT7kFCrxpfU3Q5zx8+uSyVw5Q2VDoFMlQUcnaRsYaytV++v08TZdim/rQAZ3lPfh2NhmhXKx3ADgCbbxf+iQowwuIlZBNPWeZZw7Dp1ytieH+3ZOZn0DMahWxd40uTuldcw7IBVOwy0tVPmYpNVl5CjZcctAZ7fuaUSxq5fh2Cmmywvp2AC2XxXwDPd+zENXqez8UOxnfmJuUu+3xwGqy1dh6WButj48vR1ukIZwnirhuHjFADHC7Rl/D9wgmOnAjGywtuy0gTxCqJ1IeOXy+bLkIObF7tI78QfdoL+0CVoU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
